### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [huxingyi/libphone#1]
I would like to point out that an identifier like "[`__LIBPHONE_H__`](https://github.com/huxingyi/libphone/blob/fe7c2b19705fd271b93edc93595dc2ad4a4f7062/include/libphone.h#L16)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by huxingyi** [comment]
Looks like a robot, well, close then.

**Comment by elfring** [comment]
How do you think about to avoid that your software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?
