### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [huxingyi/libphone#2]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [phoneInitApplication](https://github.com/huxingyi/libphone/blob/fe7c2b19705fd271b93edc93595dc2ad4a4f7062/src/libphone.c#L27)
- [shareMalloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [shareCreateThread](https://github.com/huxingyi/libphone/blob/fe7c2b19705fd271b93edc93595dc2ad4a4f7062/src/ios/iosphone.m#L1134)

**Comment by huxingyi** [comment]
Looks like a robot, well, close then.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for your software?
