### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [huxingyi/libphone#3]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [createTexForImage](https://github.com/huxingyi/libphone/blob/6ac8f335bdd0566d318a016324f2d4e59422efd1/samples/rpggame/rpggame.c#L98 "Improve createTexForImage function?")
* [shareRemoveThread](https://github.com/huxingyi/libphone/blob/fe7c2b19705fd271b93edc93595dc2ad4a4f7062/src/ios/iosphone.m#L1169 "Improve shareRemoveThread function?")

**Comment by huxingyi** [comment]
Looks like a robot, well, close then.

**Comment by elfring** [comment]
Another small source code improvement would be nice, wouldn't it?
