### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by flatr0ze** [huxingyi/libphone#4]
Hello. Great project, just one but: there's no such thing as "MIT License". https://en.wikipedia.org/wiki/MIT_License

You'd have to release it under X11 or some sort of Apache/CC license in order for people to be able to use it freely. Currently there's no LICENSE file in the root of the repository and it may hold this awesome project back from being widely used.

GPL is perhaps not a good idea for this project since it's not a tool but rather a piece of code (therefore it'd infect every app built with this framework). I'd say you need to consult with people who know enough about software licenses in order for libphone to become more popular.

Keep up the good work, thank you for sharing this framework.

**Comment by huxingyi** [comment]
Thanks for addressing this issue. I have added the missing LICENSE file. If there is any problem with the LICENSE, please don't hesitate to comment and drop a pull request.

**Comment by huxingyi** [comment]
I am closing this issue. Please feel free to comment more.

**Comment by flatr0ze** [comment]
Thank you.
